/**
 * DS-STAR Analytics Types
 * Autonomous data science agent with self-correction
 */

/**
 * DS-STAR analysis request
 */
export interface DSStarRequest {
  query: string;
  data?: any;
  context?: Record<string, any>;
  maxIterations?: number;
}

/**
 * Analysis plan from Planner agent
 */
export interface AnalysisPlan {
  steps: PlanStep[];
  dataRequirements: string[];
  expectedOutputs: string[];
  estimatedTime: number;
}

/**
 * Individual step in analysis plan
 */
export interface PlanStep {
  stepNumber: number;
  description: string;
  method: string;
  inputs: string[];
  expectedOutput: string;
}

/**
 * Code generated by Coder agent
 */
export interface GeneratedCode {
  code: string;
  language: 'python' | 'r' | 'sql';
  dependencies: string[];
  explanation: string;
}

/**
 * Verification result from Verifier agent
 */
export interface VerificationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  confidence: number;
  suggestions?: string[];
}

/**
 * Execution result
 */
export interface ExecutionResult {
  success: boolean;
  output?: any;
  error?: string;
  executionTime: number;
  logs: string[];
}

/**
 * Complete DS-STAR analysis result
 */
export interface DSStarResult {
  query: string;
  plan: AnalysisPlan;
  code: GeneratedCode;
  verification: VerificationResult;
  execution: ExecutionResult;
  iterations: number;
  totalTime: number;
  finalAnswer: string;
}

/**
 * DS-STAR agent roles
 */
export enum DSStarRole {
  PLANNER = 'PLANNER',
  CODER = 'CODER',
  VERIFIER = 'VERIFIER',
  ROUTER = 'ROUTER',
  DATA_PROCESSOR = 'DATA_PROCESSOR'
}

/**
 * Analysis status
 */
export enum AnalysisStatus {
  PLANNING = 'PLANNING',
  CODING = 'CODING',
  VERIFYING = 'VERIFYING',
  EXECUTING = 'EXECUTING',
  CORRECTING = 'CORRECTING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

/**
 * DS-STAR configuration
 */
export interface DSStarConfig {
  openaiApiKey: string;
  model?: string;
  maxIterations?: number;
  timeout?: number;
  enableSelfCorrection?: boolean;
}

/**
 * Iteration record for tracking corrections
 */
export interface IterationRecord {
  iterationNumber: number;
  plan: AnalysisPlan;
  code: GeneratedCode;
  verification: VerificationResult;
  execution?: ExecutionResult;
  correctionReason?: string;
  timestamp: Date;
}
